version: '3.8'

services:

  app:
    build: .
    depends_on:
      - db
    ports:
      - 8080:8080

  db:
    image: postgres:15.2
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
